apiVersion: apps/v1
kind: Deployment
metadata:
  name: missing-table-celery-worker-prod
  namespace: match-scraper
  labels:
    app: missing-table-worker
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: missing-table-worker
      environment: prod
  template:
    metadata:
      labels:
        app: missing-table-worker
        environment: prod
    spec:
      restartPolicy: Always
      containers:
      - name: celery-worker
        image: missing-table-worker:latest
        imagePullPolicy: Never  # Use local image
        command: ["/app/docker-entrypoint.sh"]
        args:
          - "worker"
          - "--loglevel=info"
          - "--queues=matches.prod"
          - "--concurrency=4"
        env:
        # RabbitMQ/Celery Configuration
        - name: RABBITMQ_URL
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: RABBITMQ_URL
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: CELERY_RESULT_BACKEND
        # Supabase Configuration
        - name: SUPABASE_URL
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: SUPABASE_URL
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              name: missing-table-worker-prod-secrets
              key: SUPABASE_KEY
        - name: SUPABASE_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: missing-table-worker-prod-secrets
              key: SUPABASE_JWT_SECRET
        - name: SERVICE_ACCOUNT_SECRET
          valueFrom:
            secretKeyRef:
              name: missing-table-worker-prod-secrets
              key: SERVICE_ACCOUNT_SECRET
        # Application Configuration
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: missing-table-worker-prod-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
