repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: diff-cover
        name: diff-cover
        entry: bash -c 'uv run pytest tests/unit/ --cov=src --cov-report=xml -q && uv run diff-cover coverage.xml --compare-branch=main --fail-under=80'
        language: system
        pass_filenames: false
        files: ^src/.*\.py$
        stages: [commit]

  # Moved slow checks to CI only for faster local development
  # Uncomment these for thorough local checking when needed:
  #
  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: uv run pytest tests/unit/ -x --tb=short
  #       language: system
  #       pass_filenames: false
  #       always_run: true
  #
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.18.2
  #   hooks:
  #     - id: mypy
  #       files: ^src/
  #       additional_dependencies: [types-requests]
  #       args: [--strict, --no-error-summary]
