apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"initContainers":[{"name":"config-preprocessor"}],"containers":[{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"1Gi"},"name":"mls-scraper"},{"limits":{"cpu":"200m","ephemeral-storage":"1Gi","memory":"256Mi"},"requests":{"cpu":"100m","ephemeral-storage":"1Gi","memory":"128Mi"},"name":"promtail"}]},"output":{"initContainers":[{"limits":{"ephemeral-storage":"2Gi"},"requests":{"cpu":"600m","ephemeral-storage":"2Gi","memory":"1152Mi"},"name":"config-preprocessor"}],"containers":[{"limits":{"cpu":"1","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"1Gi"},"name":"mls-scraper"},{"limits":{"cpu":"200m","ephemeral-storage":"1Gi","memory":"256Mi"},"requests":{"cpu":"100m","ephemeral-storage":"1Gi","memory":"128Mi"},"name":"promtail"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.19-gke.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"labels":{"app":"mls-scraper"},"name":"mls-scraper-cronjob","namespace":"match-scraper"},"spec":{"concurrencyPolicy":"Forbid","failedJobsHistoryLimit":3,"jobTemplate":{"spec":{"template":{"metadata":{"labels":{"app":"mls-scraper"}},"spec":{"containers":[{"command":["python","-m","src.cli.main","scrape"],"env":[{"name":"AGE_GROUP","valueFrom":{"configMapKeyRef":{"key":"AGE_GROUP","name":"mls-scraper-config"}}},{"name":"DIVISION","valueFrom":{"configMapKeyRef":{"key":"DIVISION","name":"mls-scraper-config"}}},{"name":"MISSING_TABLE_API_BASE_URL","valueFrom":{"configMapKeyRef":{"key":"MISSING_TABLE_API_BASE_URL","name":"mls-scraper-config"}}},{"name":"LOG_LEVEL","valueFrom":{"configMapKeyRef":{"key":"LOG_LEVEL","name":"mls-scraper-config"}}},{"name":"HEADLESS","valueFrom":{"configMapKeyRef":{"key":"HEADLESS","name":"mls-scraper-config"}}},{"name":"BROWSER_TIMEOUT","valueFrom":{"configMapKeyRef":{"key":"BROWSER_TIMEOUT","name":"mls-scraper-config"}}},{"name":"MAX_RETRIES","valueFrom":{"configMapKeyRef":{"key":"MAX_RETRIES","name":"mls-scraper-config"}}},{"name":"RETRY_DELAY","valueFrom":{"configMapKeyRef":{"key":"RETRY_DELAY","name":"mls-scraper-config"}}},{"name":"DEPLOYMENT_ENV","valueFrom":{"configMapKeyRef":{"key":"DEPLOYMENT_ENV","name":"mls-scraper-config"}}},{"name":"K8S_NAMESPACE","valueFrom":{"configMapKeyRef":{"key":"K8S_NAMESPACE","name":"mls-scraper-config"}}},{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","valueFrom":{"configMapKeyRef":{"key":"OTEL_EXPORTER_OTLP_ENDPOINT","name":"mls-scraper-config"}}},{"name":"OTEL_METRIC_EXPORT_INTERVAL","valueFrom":{"configMapKeyRef":{"key":"OTEL_METRIC_EXPORT_INTERVAL","name":"mls-scraper-config"}}},{"name":"OTEL_METRIC_EXPORT_TIMEOUT","valueFrom":{"configMapKeyRef":{"key":"OTEL_METRIC_EXPORT_TIMEOUT","name":"mls-scraper-config"}}},{"name":"MISSING_TABLE_API_TOKEN","valueFrom":{"secretKeyRef":{"key":"MISSING_TABLE_API_TOKEN","name":"mls-scraper-secrets"}}},{"name":"OTEL_EXPORTER_OTLP_HEADERS","valueFrom":{"secretKeyRef":{"key":"OTEL_EXPORTER_OTLP_HEADERS","name":"mls-scraper-secrets"}}}],"image":"gcr.io/missing-table/mls-scraper:latest","imagePullPolicy":"Always","name":"mls-scraper","resources":{"limits":{"cpu":"1000m","memory":"2Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"drop":["ALL"]},"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1000},"volumeMounts":[{"mountPath":"/var/log/scraper","name":"logs"}]},{"args":["-config.file=/etc/promtail/promtail.yaml"],"image":"grafana/promtail:2.9.3","name":"promtail","resources":{"limits":{"cpu":"200m","memory":"256Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"volumeMounts":[{"mountPath":"/var/log/scraper","name":"logs","readOnly":true},{"mountPath":"/etc/promtail","name":"promtail-processed"}]}],"initContainers":[{"args":["envsubst \u003c /etc/promtail-template/promtail.yaml \u003e /etc/promtail-processed/promtail.yaml\necho \"Promtail config processed successfully\"\necho \"Config file size: $(wc -c \u003c /etc/promtail-processed/promtail.yaml) bytes\"\n"],"command":["/bin/sh","-c"],"env":[{"name":"LOKI_USER_ID","valueFrom":{"secretKeyRef":{"key":"LOKI_USER_ID","name":"mls-scraper-secrets"}}},{"name":"LOKI_API_KEY","valueFrom":{"secretKeyRef":{"key":"LOKI_API_KEY","name":"mls-scraper-secrets"}}}],"image":"bhgedigital/envsubst:latest","name":"config-preprocessor","volumeMounts":[{"mountPath":"/etc/promtail-template","name":"promtail-config"},{"mountPath":"/etc/promtail-processed","name":"promtail-processed"}]}],"restartPolicy":"OnFailure","volumes":[{"emptyDir":{},"name":"logs"},{"configMap":{"name":"promtail-config"},"name":"promtail-config"},{"emptyDir":{},"name":"promtail-processed"}]}}}},"schedule":"0 6 * * *","successfulJobsHistoryLimit":3,"timeZone":"UTC"}}
  creationTimestamp: "2025-10-04T17:36:02Z"
  generation: 9
  labels:
    app: mls-scraper
  name: mls-scraper-cronjob
  namespace: match-scraper
  resourceVersion: "1759903200589231007"
  uid: 69273824-4cab-4eca-9481-7e3f914b1e1e
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: mls-scraper
        spec:
          containers:
          - command:
            - python
            - -m
            - src.cli.main
            - scrape
            env:
            - name: AGE_GROUP
              valueFrom:
                configMapKeyRef:
                  key: AGE_GROUP
                  name: mls-scraper-config
            - name: DIVISION
              valueFrom:
                configMapKeyRef:
                  key: DIVISION
                  name: mls-scraper-config
            - name: MISSING_TABLE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: MISSING_TABLE_API_BASE_URL
                  name: mls-scraper-config
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: mls-scraper-config
            - name: HEADLESS
              valueFrom:
                configMapKeyRef:
                  key: HEADLESS
                  name: mls-scraper-config
            - name: BROWSER_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: BROWSER_TIMEOUT
                  name: mls-scraper-config
            - name: MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  key: MAX_RETRIES
                  name: mls-scraper-config
            - name: RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  key: RETRY_DELAY
                  name: mls-scraper-config
            - name: DEPLOYMENT_ENV
              valueFrom:
                configMapKeyRef:
                  key: DEPLOYMENT_ENV
                  name: mls-scraper-config
            - name: K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: K8S_NAMESPACE
                  name: mls-scraper-config
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
                  name: mls-scraper-config
            - name: OTEL_METRIC_EXPORT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: OTEL_METRIC_EXPORT_INTERVAL
                  name: mls-scraper-config
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: OTEL_METRIC_EXPORT_TIMEOUT
                  name: mls-scraper-config
            - name: MISSING_TABLE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MISSING_TABLE_API_TOKEN
                  name: mls-scraper-secrets
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  key: OTEL_EXPORTER_OTLP_HEADERS
                  name: mls-scraper-secrets
            image: gcr.io/missing-table/mls-scraper:latest
            imagePullPolicy: Always
            name: mls-scraper
            resources:
              limits:
                cpu: "1"
                ephemeral-storage: 1Gi
                memory: 2Gi
              requests:
                cpu: 500m
                ephemeral-storage: 1Gi
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
              runAsNonRoot: true
              runAsUser: 1000
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/log/scraper
              name: logs
          - args:
            - -config.file=/etc/promtail/promtail.yaml
            image: grafana/promtail:2.9.3
            imagePullPolicy: IfNotPresent
            name: promtail
            resources:
              limits:
                cpu: 200m
                ephemeral-storage: 1Gi
                memory: 256Mi
              requests:
                cpu: 100m
                ephemeral-storage: 1Gi
                memory: 128Mi
            securityContext:
              capabilities:
                drop:
                - NET_RAW
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /var/log/scraper
              name: logs
              readOnly: true
            - mountPath: /etc/promtail
              name: promtail-processed
          dnsPolicy: ClusterFirst
          initContainers:
          - args:
            - |
              envsubst < /etc/promtail-template/promtail.yaml > /etc/promtail-processed/promtail.yaml
              echo "Promtail config processed successfully"
              echo "Config file size: $(wc -c < /etc/promtail-processed/promtail.yaml) bytes"
            command:
            - /bin/sh
            - -c
            env:
            - name: LOKI_USER_ID
              valueFrom:
                secretKeyRef:
                  key: LOKI_USER_ID
                  name: mls-scraper-secrets
            - name: LOKI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LOKI_API_KEY
                  name: mls-scraper-secrets
            image: bhgedigital/envsubst:latest
            imagePullPolicy: Always
            name: config-preprocessor
            resources:
              limits:
                ephemeral-storage: 2Gi
              requests:
                cpu: 600m
                ephemeral-storage: 2Gi
                memory: 1152Mi
            securityContext:
              capabilities:
                drop:
                - NET_RAW
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /etc/promtail-template
              name: promtail-config
            - mountPath: /etc/promtail-processed
              name: promtail-processed
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 30
          tolerations:
          - effect: NoSchedule
            key: kubernetes.io/arch
            operator: Equal
            value: amd64
          volumes:
          - emptyDir: {}
            name: logs
          - configMap:
              defaultMode: 420
              name: promtail-config
            name: promtail-config
          - emptyDir: {}
            name: promtail-processed
  schedule: 0 6 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
  timeZone: UTC
status:
  active:
  - apiVersion: batch/v1
    kind: Job
    name: mls-scraper-cronjob-29331720
    namespace: match-scraper
    resourceVersion: "1759903200543887017"
    uid: daa2ccc7-43c9-437f-b990-d97617469d5d
  lastScheduleTime: "2025-10-08T06:00:00Z"
  lastSuccessfulTime: "2025-10-07T09:52:10Z"
