"""What to scrape, derived from the feeds rather than typed out.

Until SB-1024 the Homegrown targets were a hand-written list covering
Northeast, plus Florida at U13/U14. MLS Next runs eight Homegrown conferences
at six age groups, so forty of the forty-eight brackets were never scraped and
nothing said so: a bracket nobody typed produced no target, no target produced
no matches, and no matches produced no complaint. missing-table had been
advertising the empty divisions as ``bootstrap_divisions`` all season.

The standings feed already answers the question the list was trying to. It
declares one ``competition_bracket`` per conference x age group, and
:class:`~src.scraper.assist_client.AssistIndex` is built from it on every run,
so the authoritative set of brackets is downloaded before any decision is made.
Reading it means a bracket MLS Next adds mid-season becomes a target on the
next run, and one that does not exist — there is no Pro Player Pathway bracket
at U15 — never becomes a target at all.

Target keys are stable across this change: the naming rules below reproduce
every key the hand-written list and the Flex/Pathway generators used, so the
run journal, the Telegram report and ``--target`` keep working on the names
they already knew.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import TYPE_CHECKING

import structlog

if TYPE_CHECKING:
    from src.scraper.assist_client import AssistIndex

logger = structlog.get_logger()

# Which feed carries each league, and how missing-table names the bracket.
#
# Homegrown and Flex file a bracket as a `division`; Academy files it as a
# `conference`. That difference is missing-table's, mirrored here because the
# scraper config is passed through to the queue message unchanged.
LEAGUE_FEEDS: dict[str, str] = {
    "Homegrown": "league",
    "Flex": "flex",
    "Academy": "academy",
}

BRACKET_FIELD: dict[str, str] = {
    "Homegrown": "division",
    "Flex": "division",
    "Academy": "conference",
}

# The conference whose targets carry no suffix, for historical reasons: these
# were the first targets the agent had, and their keys are in the journal.
UNSUFFIXED: dict[str, str] = {
    "Homegrown": "Northeast",
    "Academy": "New England",
}

# Senior brackets for the pro-academy clubs, inside the Homegrown league.
# Keyed as `-ppp-` rather than `-hg-` because that is what they were called
# when they were generated by hand (SB-827).
PATHWAY_SUFFIX = " (Pro Player Pathway)"

# Short label per league, used in target keys.
LEAGUE_SLUG: dict[str, str] = {
    "Homegrown": "hg",
    "Flex": "flex",
    "Academy": "academy",
}

# Targets that scrape a whole bracket but report on one team. The planner
# skips them; `--target` uses them for a single club's fixtures.
TEAM_FILTER_TARGETS: dict[str, str] = {
    "u14-hg-ifa": "IFA",
    "u13-hg-ifa": "IFA",
    "u15-hg-ifa": "IFA",
    "u16-hg-ifa": "IFA",
    "u14-academy-ifa": "IFA Academy",
}


def slug(name: str) -> str:
    """Bracket name to key fragment: 'Mid-America (East)' -> 'mid-america-east'."""
    return name.lower().replace(" (", "-").replace(")", "").replace(" ", "-")


def target_key(league: str, bracket: str, age_group: str) -> str:
    """The key for one bracket, matching the names these targets already had."""
    age = age_group.lower()
    if league == "Homegrown" and bracket.endswith(PATHWAY_SUFFIX):
        return f"{age}-ppp-{slug(bracket.removesuffix(PATHWAY_SUFFIX))}"
    if bracket == UNSUFFIXED.get(league):
        return f"{age}-{LEAGUE_SLUG[league]}"
    return f"{age}-{LEAGUE_SLUG[league]}-{slug(bracket)}"


def build_targets(
    indexes: Mapping[str, AssistIndex],
    *,
    leagues: Iterable[str] = ("Homegrown", "Flex"),
) -> dict[str, dict[str, str]]:
    """Every bracket the given feeds declare, as scraper configs.

    Args:
        indexes: Feed name -> the index built from that feed's standings.
            A league whose feed is absent contributes nothing, which is how a
            season that has not published one yet is survived.
        leagues: Which leagues to build targets for. Academy is opt-in: its
            271 clubs are mostly unknown to missing-table, and a target whose
            teams cannot be resolved drops its matches and reports a name
            failure for each one (SB-1018).

    Returns:
        Target key -> scraper config, ready for the planner.
    """
    targets: dict[str, dict[str, str]] = {}
    for league in leagues:
        feed = LEAGUE_FEEDS.get(league)
        index = indexes.get(feed) if feed else None
        if index is None:
            logger.warning("targets.feed_missing", league=league, feed=feed)
            continue

        field = BRACKET_FIELD[league]
        for bracket, age_group in sorted(index.brackets):
            targets[target_key(league, bracket, age_group)] = {
                "age_group": age_group,
                "league": league,
                field: bracket,
            }

    for key, _team in TEAM_FILTER_TARGETS.items():
        base = key.removesuffix("-ifa")
        if base in targets:
            targets[key] = dict(targets[base])

    logger.info(
        "targets.built",
        count=len(targets),
        leagues=sorted(leagues),
    )
    return targets


async def load_targets(
    *,
    leagues: Iterable[str] = ("Homegrown", "Flex"),
    client: object | None = None,
) -> dict[str, dict[str, str]]:
    """Fetch the standings feeds and build the targets they declare.

    The feeds are cached and revalidated, so this costs a 304 on a run where
    nothing changed (SB-884) and is shared with the scrape that follows.
    """
    from src.scraper.assist_client import AssistClient

    async def _load(c) -> dict[str, dict[str, str]]:
        indexes = {}
        for league in leagues:
            feed = LEAGUE_FEEDS[league]
            if feed in indexes:
                continue
            try:
                indexes[feed] = await c.index(feed)
            except Exception as exc:  # noqa: BLE001 — a missing feed is not fatal
                logger.warning("targets.index_failed", feed=feed, error=str(exc))
        return build_targets(indexes, leagues=leagues)

    if client is not None:
        return await _load(client)
    async with AssistClient() as owned:
        return await _load(owned)
