apiVersion: v1
kind: ConfigMap
metadata:
  name: mls-scraper-config
  namespace: match-scraper
  labels:
    app: mls-scraper
data:
  # MLS Configuration
  AGE_GROUP: "U14"
  DIVISION: "Northeast"
  MISSING_TABLE_API_BASE_URL: "https://dev.missingtable.com"
  
  # Logging Configuration
  LOG_LEVEL: "DEBUG"
  
  # Browser Configuration
  HEADLESS: "true"
  BROWSER_TIMEOUT: "30000"
  
  # Scraping Configuration
  MAX_RETRIES: "3"
  RETRY_DELAY: "5"
