apiVersion: batch/v1
kind: CronJob
metadata:
  name: mls-scraper-cronjob
  namespace: match-scraper
  labels:
    app: mls-scraper
spec:
  # Run daily at 6 AM UTC (matching AWS Lambda schedule)
  schedule: "0 6 * * *"
  timeZone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mls-scraper
        spec:
          restartPolicy: OnFailure
          initContainers:
          - name: config-preprocessor
            image: bhgedigital/envsubst:latest
            command: ["/bin/sh", "-c"]
            args:
              - |
                envsubst < /etc/promtail-template/promtail.yaml > /etc/promtail-processed/promtail.yaml
                echo "Promtail config processed successfully"
                echo "Config file size: $(wc -c < /etc/promtail-processed/promtail.yaml) bytes"
            env:
            - name: LOKI_USER_ID
              valueFrom:
                secretKeyRef:
                  name: mls-scraper-secrets
                  key: LOKI_USER_ID
            - name: LOKI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mls-scraper-secrets
                  key: LOKI_API_KEY
            volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail-template
            - name: promtail-processed
              mountPath: /etc/promtail-processed
          containers:
          - name: mls-scraper
            # Replace with your actual GCP Container Registry image
            image: gcr.io/missing-table/mls-scraper:latest
            imagePullPolicy: Always
            command: ["python", "-m", "src.cli.main", "scrape"]
            env:
            # Load from ConfigMap
            - name: AGE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: AGE_GROUP
            - name: DIVISION
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: DIVISION
            - name: MISSING_TABLE_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: MISSING_TABLE_API_BASE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: LOG_LEVEL
            - name: HEADLESS
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: HEADLESS
            - name: BROWSER_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: BROWSER_TIMEOUT
            - name: MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: MAX_RETRIES
            - name: RETRY_DELAY
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: RETRY_DELAY
            # Observability Configuration
            - name: DEPLOYMENT_ENV
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: DEPLOYMENT_ENV
            - name: K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: K8S_NAMESPACE
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: OTEL_METRIC_EXPORT_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: OTEL_METRIC_EXPORT_INTERVAL
            - name: OTEL_METRIC_EXPORT_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: mls-scraper-config
                  key: OTEL_METRIC_EXPORT_TIMEOUT
            # Load from Secret
            - name: MISSING_TABLE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: mls-scraper-secrets
                  key: MISSING_TABLE_API_TOKEN
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: mls-scraper-secrets
                  key: OTEL_EXPORTER_OTLP_HEADERS
            volumeMounts:
            - name: logs
              mountPath: /var/log/scraper
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "1000m"
            # Security context for running as non-root
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                - ALL

          # Promtail sidecar for log forwarding to Grafana Loki
          - name: promtail
            image: grafana/promtail:2.9.3
            args:
            - -config.file=/etc/promtail/promtail.yaml
            volumeMounts:
            - name: logs
              mountPath: /var/log/scraper
              readOnly: true
            - name: promtail-processed
              mountPath: /etc/promtail
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "200m"

          volumes:
          - name: logs
            emptyDir: {}
          - name: promtail-config
            configMap:
              name: promtail-config
          - name: promtail-processed
            emptyDir: {}
