apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: match-scraper
  labels:
    app: mls-scraper
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: ${LOKI_ENDPOINT}
        bearer_token: ${GRAFANA_CLOUD_API_TOKEN}
        batchwait: 1s
        batchsize: 1048576
        timeout: 10s

    scrape_configs:
      # Scrape stdout/stderr from the main container
      - job_name: scraper-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: mls-match-scraper
              service: mls-scraper
              environment: production
              namespace: match-scraper
              __path__: /var/log/scraper/*.log

        pipeline_stages:
          # Parse JSON logs from AWS Lambda Powertools
          - json:
              expressions:
                timestamp: timestamp
                level: level
                message: message
                service: service
                operation: operation

          # Set timestamp from log entry
          - timestamp:
              source: timestamp
              format: RFC3339

          # Set log level
          - labels:
              level:
              service:
              operation:

          # Output the message
          - output:
              source: message
