apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: match-scraper
  labels:
    app: mls-scraper
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: https://logs-prod-036.grafana.net/loki/api/v1/push
        basic_auth:
          username: ${LOKI_USER_ID}
          password: ${LOKI_API_KEY}
        batchwait: 1s
        batchsize: 1048576
        timeout: 10s

    scrape_configs:
      - job_name: scraper-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: mls-match-scraper
              service: mls-scraper
              environment: production
              namespace: match-scraper
              __path__: /var/log/scraper/*.log

        pipeline_stages:
          - json:
              expressions:
                timestamp: timestamp
                level: level
                message: message
                service: service
                operation: operation

          - timestamp:
              source: timestamp
              format: RFC3339

          - labels:
              level:
              service:

          - output:
              source: message
