apiVersion: v1
kind: Secret
metadata:
  name: mls-scraper-secrets
  namespace: match-scraper
  labels:
    app: mls-scraper
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded values
  # To encode: echo -n "your-secret-value" | base64

  # Missing Table API Token
  MISSING_TABLE_API_TOKEN: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lKelpYSjJhV05sTFcxaGRHTm9MWE5qY21Gd1pYSWlMQ0pwYzNNaU9pSnRhWE56YVc1bkxYUmhZbXhsSWl3aVlYVmtJam9pYzJWeWRtbGpaUzFoWTJOdmRXNTBJaXdpWlhod0lqb3hOell5TmprNE1qRXpMQ0pwWVhRaU9qRTNOVGsxT0RjNE1UTXNJbk5sY25acFkyVmZibUZ0WlNJNkltMWhkR05vTFhOamNtRndaWElpTENKd1pYSnRhWE56YVc5dWN5STZXeUp0WVc1aFoyVmZaMkZ0WlhNaUxDSnlaV0ZrWDNSbFlXMXpJaXdpY21WaFpGOXpaV0Z6YjI1eklpd2liV0Z1WVdkbFgzUmxZVzF6SWwwc0luSnZiR1VpT2lKelpYSjJhV05sWDJGalkyOTFiblFpZlEuak9NdGh0SENxWGhSM190US1SM2xjUHpuNjFseDhCbDBtd1Rka2VzWGk2SQ=="

  # Grafana Cloud Credentials
  # OTLP Auth Header: Format is "Authorization=Basic base64(instanceID:apiToken)"
  # To create: echo -n "instanceID:grafanaCloudToken" | base64
  # Then: echo -n "Authorization=Basic YOUR_BASE64_HERE" | base64
  # Replace with your actual Grafana Cloud OTLP token
  OTEL_EXPORTER_OTLP_HEADERS: "QXV0aG9yaXphdGlvbj1CYXNpYyBZV05qWlhOelgzUnZhMlZ1"

  # Grafana Cloud Loki Token (for Promtail)
  # This is your Grafana Cloud API token for pushing logs to Loki
  # To encode: echo -n "your-grafana-cloud-api-token" | base64
  GRAFANA_CLOUD_API_TOKEN: "eW91ci1ncmFmYW5hLWNsb3VkLWFwaS10b2tlbg=="
