apiVersion: v1
kind: Secret
metadata:
  name: mls-scraper-secrets
  namespace: match-scraper
  labels:
    app: mls-scraper
type: Opaque
data:
  MISSING_TABLE_API_TOKEN: "ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnpkV0lpT2lKelpYSjJhV05sTFcxaGRHTm9MWE5qY21Gd1pYSWlMQ0pwYzNNaU9pSnRhWE56YVc1bkxYUmhZbXhsSWl3aVlYVmtJam9pYzJWeWRtbGpaUzFoWTJOdmRXNTBJaXdpWlhod0lqb3hOell5TmprNE1qRXpMQ0pwWVhRaU9qRTNOVGsxT0RjNE1UTXNJbk5sY25acFkyVmZibUZ0WlNJNkltMWhkR05vTFhOamNtRndaWElpTENKd1pYSnRhWE56YVc5dWN5STZXeUp0WVc1aFoyVmZaMkZ0WlhNaUxDSnlaV0ZrWDNSbFlXMXpJaXdpY21WaFpGOXpaV0Z6YjI1eklpd2liV0Z1WVdkbFgzUmxZVzF6SWwwc0luSnZiR1VpT2lKelpYSjJhV05sWDJGalkyOTFiblFpZlEuak9NdGh0SENxWGhSM190US1SM2xjUHpuNjFseDhCbDBtd1Rka2VzWGk2SQ=="
  OTEL_EXPORTER_OTLP_HEADERS: "QXV0aG9yaXphdGlvbj1CYXNpYyBNVEU0TkRZMk56cG5iR05mWlhsS2RrbHFiMmxOVkUweVRWUlpNazVEU1hOSmJUUnBUMmxLZW1SSFJtcGhlVEI0VFZSbk1FNXFXVE5NVnprd1lraEJkR1F6U25Ca1IxVjBXak5LYUZwdFJuVlpVekV3WWpKMGJHSnBTWE5KYlhOcFQybEtjR1ZJU1RWYVJtaHVUbXBCZW1GNlVYcFZNbEV4WkRKNFRrMVhXVEJQUmxGcFRFTktkRWxxY0RkSmJrbHBUMmxLZDJOdE9XdE1XRlo2VEZkV2FHTXpVWFJOUTBvNVpsRTlQUT09"
  GRAFANA_CLOUD_API_TOKEN: "Z2xjX2V5SnZJam9pTVRNMk1UWTJOQ0lzSW00aU9pSnpkR0ZqYXkweE1UZzBOalkzTFc5MGJIQXRkM0pwZEdVdGIzUmxiQzEwYjJ0bGJpSXNJbXNpT2lKaFVWcEVTemd3VGpKMVFqWmFNSGxMTUVrNGFHMDNNalVpTENKdElqcDdJbklpT2lKd2NtOWtMWFZ6TFdWaGMzUXRNQ0o5ZlE9PQ=="
