# NodePort service for accessing RabbitMQ management UI from outside cluster
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: match-scraper
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 30672  # Access RabbitMQ management UI at http://localhost:30672
    protocol: TCP
  selector:
    app: rabbitmq
