apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: match-scraper
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
    protocol: TCP
  - name: management
    port: 15672
    targetPort: 15672
    protocol: TCP
  - name: prometheus
    port: 15692
    targetPort: 15692
    protocol: TCP
  selector:
    app: rabbitmq
